### PR TITLE
Ben's Auth System

### PR DESCRIPTION
**Pull request by Rooster202**
Great sign in/ sign out system made by ben

### CODE REVIEW

**Comment by Rooster202** [comment]
bbmbm

**Comment by Rooster202** [comment]
Woops, didn't mean to do that lol

**Comment by Rooster202** [comment]
OOOOOOo i can reopen it.

**Comment by Rooster202** [comment]
Epiccccccc

**Comment by Rooster202** [comment]
@tranjamin @Nebrok This gonna be great

**Comment by Rooster202** [comment]
#2 Yo @Nebrok you didn't do this code properly. I WANT IT ON MY DESK TOMORROW 7AM SHARP. DO IT RIGHT THIS TIME

**Comment by tranjamin** [comment]
@Rooster202 I'm not surprised. Those Maccas employees never do it right. We should give him a pay cut

**Comment by Nebrok** [comment]
Me @Rooster202 This code was the little vietnamese boy

**Pull request merged**
